version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    env_file:
      - ./.env
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    container_name: todo-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pwd_123
      POSTGRES_DB: postgres